### ISSUE TITLE
Cancel button on SwingIdentityKeyChooser doesn't seem to cancel

### ISSUE THREAD

**Issue by dtuma** [MoebiusSolutions/cac-agent#25]
Thank you for writing the cac-agent library! It's been a godsend. It's saved me countless hours as I CAC-enable a Java Swing application.

I've observed one possible issue. To reproduce, take these steps:

1. Run the `com.moesol.url.DumpURL` class, pointing to a URL that requires client authentication
2. The "Select Identity" dialog is displayed
3. Instead of selecting an identity, press the Cancel button
4. The "Select Identity" dialog is displayed again
5. Repeat steps 3 and 4 again and again and again

For an end-user-facing app, it seems important for the Cancel button to work as expected; so I'd like to find a resolution.

**Comment by dtuma** [comment]
This behavior varies from one version of Java to another:

- On Java 8, I have to cancel 16 times before the dialog finally goes away
- Everything seems to work as expected on Java 9 and 10
- On Java 11 and 14, I have to cancel 14 times

I came across [this Java bug report](https://bugs.openjdk.java.net/browse/JDK-8262186) that appears to be related. That bug is present in many versions of Java, so this cancel loop will occur for anyone using one of those Java versions. Java 8 is still widely used by many organizations that prefer Oracle's old licensing scheme, so a workaround in cac-agent could be helpful.

Some servers send a redirect on auth failure that makes the problem even worse. An example I came across was https://www.homeport.navy.mil which triggers a painfully long loop. On Java 8, I had to cancel 180 times before the dialog finally went away. But notably, that server still triggers a 20-step-long cancel loop on Java 9 and 10, where the Java bug is not present. For comparison, web browsers do not repeatedly display the certificate selection dialog for that website when I press cancel.

I'm thinking the resolution might be to return null from `AbstractSelectorKeyManager.chooseClientAlias` if:

- The previous call to `chooser.chooseFromAliases` returned null, and
- This new request seems to be a duplicate of the earlier call.

Is that what you would recommend? Or would it be better to throw a runtime exception? I'm not familiar with the architecture of `X509ExtendedKeyManager` so I would appreciate your advice.

**Comment by moesol** [comment]
I'm on leave until next week, so I have limited tools to test. If you can get `return null` to work that would be more inline with exceptions being exceptional conditions. However, I don't recall at this time where the loop originates from, so you may have to resource to throwing a custom runtime exception to break out of the loop. You might be able to use a debugger/breakpoint to get an idea of the loop that keeps prompting after the cancel button. Also, it might also be possible to register a callback to handle the cancel button and close the dialog.

**Comment by dtuma** [comment]
> Also, it might also be possible to register a callback to handle the cancel button and close the dialog.

The cancel button does close the dialog successfully, returning null as the chosen alias. So that's good news: all is working fine on the Swing side.

> You might be able to use a debugger/breakpoint to get an idea of the loop that keeps prompting after the cancel button.

It seems that [sun.security.ssl.X509Authentication](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.base/share/classes/sun/security/ssl/X509Authentication.java) contains a loop that calls `AbstractSelectorKeyManager.chooseClientAlias` again immediately. There might be other loops higher in the call stack that are also contributing; it's hard to tell since my JDK doesn't include source code for the `sun.*` classes.

In those subsequent calls, `choosenAlias` is null, so the branch that would return a cached alias is skipped. Instead, it falls through and asks the chooser to display the dialog again.

I seem to be having success with the `return null` approach. I'll test a bit more, and possibly suggest a patch when you're back at work. (Thank you for such a quick reply while on leave!)

**Comment by moesol** [comment]
OK, I'll stand down until I hear back from you. If you submit a merge request, I'll try to get to it quickly.

**Comment by dtuma** [comment]
I've submitted pull request #26 for this. Thank you for your help.
